### ISSUE TITLE
Not working `playershoot` and `moveplayer` calls

### ISSUE THREAD

**Issue by akowalew** [eatrunner/tank-game#1]
While game is created and running, some API calls don't work.

`http://127.0.0.1:9000/tank-game/ajax/game/moveplayer/?game_id=0&id=0&dir=up`
produces
```myapp ajax error: Traceback (most recent call last): File "/home/akowalew/workspace/tank-game/build_web/config/views.py", line 36, in ajax data = json.dumps( fun(request.GET )) File "/home/akowalew/workspace/tank-game/build_web/game/views.py", line 193, in moveplayer self.game_threads_[int(params['game_id'])].moveTank(int(params['id']), params['dir']) File "/home/akowalew/workspace/tank-game/build_web/../game/Game.py", line 48, in moveTank if (tank.move(direction)): AttributeError: 'int' object has no attribute 'move'```

and

`http://127.0.0.1:9000/tank-game/ajax/game/playershoot/?game_id=0&id=0`
produces
`myapp ajax error: Traceback (most recent call last): File "/home/akowalew/workspace/tank-game/build_web/config/views.py", line 36, in ajax data = json.dumps( fun(request.GET )) File "/home/akowalew/workspace/tank-game/build_web/game/views.py", line 210, in playershoot self.game_threads_[params['game_id']].shoot(params['id']) TypeError: list indices must be integers, not unicode`

**Comment by eatrunner** [comment]
solved on branch eatrunner
