### ISSUE TITLE
[Proposal] Needed requests and responses

### ISSUE THREAD

**Issue by akowalew** [eatrunner/tank-game#2]
# Game API functions that are needed

**[notice]** Every request should return at least JSON with `errors` property.
**[notice2]** When game is created, in every moment, after a specified timeout (e.g. 1 minute) and after no interraction from client side, server **must** destroy created game.

### `\getavailmaps`
* Returns JSON with array of available `map_id`'s

### `\creategame\?map_id=...`
* It creates a new game which starts at map pointed by `map_id`.
* Game is not running after this.
* Returns JSON with `gameId` to created game. 

### `\getgameinfo\?game_id=...`
* Returns JSON that describes game at the very beginning: `mapWidth`, `mapHeight`, `map`,
* Should be called before `startgame` or `continuegame`

### `\startgame\?game_id=...`
* Starts the game thread,
* Returns JSON with `playerId` property.

### `\deletegame\?game_id=...`
* Removes game from server. All further requests with this `game_id` should not be accepted,

### `\pausegame\?game_id=...`
* Game is paused.
* May be resumed with `resumegame`

### `\resumegame\?game_id=...`
* Resumes the game.

### `\continuegame\?game_id=...`
* Only If player won the map, it allows to go to the next map
* Returns JSON with `playerId`

### `\getstate\?game_id=...`
* May be called only when game is running, when player are defeated or when player won the game.
* Example JSON response:
```JSON
{
 "errors": "",
 "map": [ ... ] ,
 "tanks": [ {...}, {...}, ... ] ,
 "bullets": [ {...}, {...}, ... ] ,
 "bonuses": [ {...}, {...}, ... ] ,
 "status": ... ,
 "score": 4300
}
```
* `map`:
   * Contains in one array whole map, as much items, as map size is.
   * `E` - empty, `B` - brick, `S` - stone, `P` - platform, `W` - water, `G` - grass
```JSON
"map": [ "E", "B", "S", "P", ... ],
```
* `tanks`:
   * Contains array with every tank definition. 
   * `id` is an individual tank ID, `direction` can be `up`, `down`, `right`, `left`, `bonus` may be `armor`, `weapon`, `waterarmor` etc
```JSON
"tanks": [
 {
  "id": 0,
  "playerId": 1,
  "x": 12, "y": 1,
  "direction": "down",
  "bonus": ""
 },
 {
  "id": 1,
  "playerId": 0,
  "x": 1, "y": 3,
  "direction": "right",
  "bonus": "armor"
 }
] ,
```
* `bullets`:
   * Contains array with every bullet definition.
   * `id` is an individual bullet ID, `ownerId` is an ID of tank, which has created this bullet.
```JSON
"bullets": [
 {
  "id": 0,
  "x": 1, "y": 2,
  "direction": "up",
  "ownerId": 0
 },
 {
  "id": 2,
  "x": 4, "y": 3,
  "direction": "right",
  "ownerId": 1
 }
] ,
```
* `bonuses`:
   * Contains array with every bonus definition.
   * `id` is an individual bonus ID, `type` may be `armor`, `weapon`, `waterarmor`, `bomb`, `timer`,  etc
```JSON
"bonuses": [
 {
  "id": 0,
  "x": 1, "y": 2,
  "type": "bomb"
 },
 {
  "id": 2,
  "x": 4, "y": 1,
  "type": "armor"
 }
] ,
```
* `status` possible values: `run`, `win`, `lose`
* `score` is an ammount of points collected by player

### `\getsummary\?game_id=...`
* Returns JSON with `score`:  points collected by player
* (Not important now) Returns bonuses collected by player,
* (Not important now) Returns tanks killed by player,

# How to use theese functions

## To play a game:
1. `\creategame` -> `gameId`
2. `\getgameinfo(gameId)` -> `{ "map": ..., "mapWidth": ..., "mapHeight": ... }`
3. `\stargame(gameId)` -> `{ "playerId" : ... }`
4. `\getstate(gameId)` -> `{ "map": ..., "bullets": ..., "tanks": ..., "bonuses": ..., "score": ..., "status": ... }`
5. Go to step 4. while `state` = `run`

##  When `state` = `lose`:
1. `\getsummary` -> `{ "score": ..., ... }`
2. `\deletegame` -> `{ }`

## When `state` = `win`:
1. `\getsummary` -> `{ "score": ..., ... }`
2. If player wants to play next level:
   1. `\getgameinfo(gameId)` -> `{ "map": ..., "mapWidth": ..., "mapHeight": ... }`
   2. `\continuegame(gameId)` -> `{ "playerId": ... }
3. If player doesn't want to play: 
   1. `\deletegame(gameId)`

## When `state` = `run`
1. `\pausegame(gameId)`
2. `\resumegame(gameId)` OR `\deletegame(gameId)`

**Comment by eatrunner** [comment]
\creategame\?map_id=... solved
\getgameinfo\?game_id=... solved
\startgame\?game_id=... solved
\deletegame\?game_id=... solved
\pausegame\?game_id=... solved
\resumegame\?game_id=... solved
\continuegame\?game_id=... solved
\getstate\?game_id=... solved
on branch eatrunner

**Comment by eatrunner** [comment]
solved
