### ISSUE TITLE
Bad working `creategame` request

### ISSUE THREAD

**Issue by akowalew** [eatrunner/tank-game#3]
# `creategame` is not working well

After typing `http://localhost:9000/tank-game/ajax/game/creategame/map_id=0` (`map_id=1` also) server is returning `{"gameid": 0, "error": ""}`, but then if I check this game with `http://127.0.0.1:9000/tank-game/ajax/game/getgameinfo/?gameid=2` I'm getting response `{"map": [], "mapHeight": 0, "mapWidth": 0, "error": ""}`

Other two mistakes:
1. `getgameinfo` should accept `game_id`, **not** `gameid`
2. If I don't specify `map_id` inside `creategame`, server accepts this error, but it should not. After calling `http://localhost:9000/tank-game/ajax/game/creategame/` I'm getting `{"gameid": 1, "error": ""}`. Not good.

**Comment by akowalew** [comment]
Please specify, @eatrunner , what I should use: `game_id` or `gameid` ? In #2 I proposed `game_id`

**Comment by eatrunner** [comment]
solved
