### ISSUE TITLE
`getavalmaps` Should not require `game_id`

### ISSUE THREAD

**Issue by akowalew** [eatrunner/tank-game#5]
After typing `http://127.0.0.1:9000/tank-game/ajax/game/getavalmaps/` I'm getting exception:
```
myapp ajax error: Traceback (most recent call last): File "/home/akowalew/workspace/tank-game/build_web/config/views.py", line 36, in ajax data = json.dumps( fun(request.GET )) File "/home/akowalew/workspace/tank-game/build_web/game/views.py", line 149, in getavalmaps if int(self.game_threads_[i]['game_id']) == int(params['game_id']): File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 322, in __getitem__ raise MultiValueDictKeyError(repr(key)) MultiValueDictKeyError: "'game_id'"
```

I believe, that `getavalmaps` does not require `game_id` parameter, because it is a global function, to be called before `creategame` request is send.

**Comment by akowalew** [comment]
@eatrunner up. Still the same problem, but now I'm getting response
```
{"error": "no existing game"}
```

**Comment by eatrunner** [comment]
server fixed. when typing 

> http://127.0.0.1:9000/tank-game/ajax/game/getavalmaps/
Gives response:

> myapp ajax error: Traceback (most recent call last): File "/home/dom/Dokumenty/workspace/tank-game/build_web/config/views.py", line 36, in ajax data = json.dumps( fun(request.GET )) File "/home/dom/Dokumenty/workspace/tank-game/build_web/game/views.py", line 144, in getavalmaps "maps":tmp.getAvalMaps(), File "/home/dom/Dokumenty/workspace/tank-game/build_web/../game/Game.py", line 20, in getAvalMaps return avalMaps NameError: global name 'avalMaps' is not defined

**Comment by akowalew** [comment]
https://github.com/eatrunner/tank-game/commit/2a6efc108086712114674bd592e1f9ea87344cf0
Fixes
